version: "3.8"

services:
    appweb:
        container_name: myapp
        build: .
        ports:
            - "5000:3000"
        links:
            - neo4j
        working_dir: /codigo
        networks:
            - mynetwork
    neo4j:
        container_name: myNeo4j
        image: neo4j:enterprise
        ports: 
            - "1000:7474"
            - "1001:7687"
        environment: 
            - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
        logging: 
            driver: none
        networks:
            - mynetwork
networks:
    mynetwork:
        driver: bridge